/**
 * Free analysis rules — generic posture/movement evaluation
 * that works for any pose, not tied to a specific test protocol.
 *
 * Thresholds are deliberately more lenient than specific test rules
 * to reduce false positives during general movement.
 */

import type { AssessmentRule } from '../../types';

export const freeAnalysisRules: AssessmentRule[] = [
  // --- General Alignment ---
  {
    id: 'fa-head-forward',
    name: 'Forward Head Position',
    testType: 'free_analysis',
    category: 'Alignment',
    metricKey: 'forwardHeadAngle',
    operator: '>',
    threshold: 15,
    severity: 'mild',
    message: 'Head appears positioned forward of the shoulder line.',
    coaching: 'Try to align your ears over your shoulders.',
  },
  {
    id: 'fa-head-forward-sig',
    name: 'Significant Forward Head',
    testType: 'free_analysis',
    category: 'Alignment',
    metricKey: 'forwardHeadAngle',
    operator: '>',
    threshold: 30,
    severity: 'moderate',
    message: 'Significant forward head position observed.',
  },
  {
    id: 'fa-shoulder-asym',
    name: 'Shoulder Asymmetry',
    testType: 'free_analysis',
    category: 'Symmetry',
    metricKey: 'shoulderHeightDiff',
    operator: 'outside',
    threshold: [-6, 6],
    severity: 'mild',
    message: 'Shoulders appear uneven — one side is higher than the other.',
  },
  {
    id: 'fa-trunk-lean',
    name: 'Trunk Lean',
    testType: 'free_analysis',
    category: 'Alignment',
    metricKey: 'trunkLean',
    operator: 'outside',
    threshold: [-8, 8],
    severity: 'mild',
    message: 'Trunk appears to lean to one side.',
    coaching: 'Try to center your weight evenly.',
  },
  {
    id: 'fa-pelvis-tilt',
    name: 'Pelvic Tilt',
    testType: 'free_analysis',
    category: 'Symmetry',
    metricKey: 'pelvicTilt',
    operator: 'outside',
    threshold: [-6, 6],
    severity: 'mild',
    message: 'Pelvis appears tilted to one side.',
  },
  {
    id: 'fa-hip-shift',
    name: 'Hip Shift',
    testType: 'free_analysis',
    category: 'Alignment',
    metricKey: 'hipShift',
    operator: '>',
    threshold: 10,
    severity: 'mild',
    message: 'Hips appear shifted laterally from center.',
  },
  {
    id: 'fa-knee-l',
    name: 'Left Knee Deviation',
    testType: 'free_analysis',
    category: 'Lower Body',
    metricKey: 'leftKneeAngle',
    operator: '>',
    threshold: 12,
    severity: 'mild',
    message: 'Left knee appears to deviate inward or outward.',
  },
  {
    id: 'fa-knee-r',
    name: 'Right Knee Deviation',
    testType: 'free_analysis',
    category: 'Lower Body',
    metricKey: 'rightKneeAngle',
    operator: '>',
    threshold: 12,
    severity: 'mild',
    message: 'Right knee appears to deviate inward or outward.',
  },
  {
    id: 'fa-weight-shift',
    name: 'Weight Distribution',
    testType: 'free_analysis',
    category: 'Balance',
    metricKey: 'weightShift',
    operator: '>',
    threshold: 12,
    severity: 'mild',
    message: 'Weight appears unevenly distributed between sides.',
  },
  {
    id: 'fa-spinal-align',
    name: 'Spinal Alignment',
    testType: 'free_analysis',
    category: 'Alignment',
    metricKey: 'spinalAlignment',
    operator: '>',
    threshold: 5,
    severity: 'mild',
    message: 'Spine appears to deviate from a straight line between head and hips.',
  },
];
