/**
 * Overhead reach, single-leg balance, and forward bend rules.
 */

import type { AssessmentRule } from '../../types';

export const overheadReachRules: AssessmentRule[] = [
  {
    id: 'or-shoulder-left-limited',
    name: 'Limited Left Shoulder Flexion',
    testType: 'overhead_reach',
    category: 'Shoulder Mobility',
    metricKey: 'leftShoulderFlexion',
    operator: '<',
    threshold: 160,
    severity: 'mild',
    message: 'Left shoulder range of motion is mildly limited during overhead reach.',
    coaching: 'Wall slides and doorway stretches can help improve shoulder mobility.',
  },
  {
    id: 'or-shoulder-right-limited',
    name: 'Limited Right Shoulder Flexion',
    testType: 'overhead_reach',
    category: 'Shoulder Mobility',
    metricKey: 'rightShoulderFlexion',
    operator: '<',
    threshold: 160,
    severity: 'mild',
    message: 'Right shoulder range of motion is mildly limited during overhead reach.',
    coaching: 'Wall slides and doorway stretches can help improve shoulder mobility.',
  },
  {
    id: 'or-shoulder-left-restricted',
    name: 'Restricted Left Shoulder Flexion',
    testType: 'overhead_reach',
    category: 'Shoulder Mobility',
    metricKey: 'leftShoulderFlexion',
    operator: '<',
    threshold: 140,
    severity: 'moderate',
    message: 'Left shoulder range of motion is moderately restricted.',
    coaching: 'Consider thoracic spine mobility work alongside shoulder stretches.',
  },
  {
    id: 'or-shoulder-right-restricted',
    name: 'Restricted Right Shoulder Flexion',
    testType: 'overhead_reach',
    category: 'Shoulder Mobility',
    metricKey: 'rightShoulderFlexion',
    operator: '<',
    threshold: 140,
    severity: 'moderate',
    message: 'Right shoulder range of motion is moderately restricted.',
    coaching: 'Consider thoracic spine mobility work alongside shoulder stretches.',
  },
  {
    id: 'or-trunk-comp',
    name: 'Trunk Compensation',
    testType: 'overhead_reach',
    category: 'Trunk Compensation',
    metricKey: 'trunkCompensation',
    operator: '>',
    threshold: 10,
    severity: 'mild',
    message: 'Trunk extends backward to compensate during overhead reach.',
    coaching: 'This may indicate shoulder or thoracic mobility limitations. Focus on lat stretches.',
  },
  {
    id: 'or-elbow-left',
    name: 'Left Elbow Flexion',
    testType: 'overhead_reach',
    category: 'Elbow Extension',
    metricKey: 'leftElbowExtension',
    operator: '<',
    threshold: 160,
    severity: 'mild',
    message: 'Left elbow does not fully extend during overhead reach.',
    coaching: 'Elbow extension stretches and tricep strengthening may help.',
  },
  {
    id: 'or-elbow-right',
    name: 'Right Elbow Flexion',
    testType: 'overhead_reach',
    category: 'Elbow Extension',
    metricKey: 'rightElbowExtension',
    operator: '<',
    threshold: 160,
    severity: 'mild',
    message: 'Right elbow does not fully extend during overhead reach.',
    coaching: 'Elbow extension stretches and tricep strengthening may help.',
  },
  {
    id: 'or-asymmetry',
    name: 'Reach Asymmetry',
    testType: 'overhead_reach',
    category: 'Asymmetry',
    metricKey: 'asymmetry',
    operator: '>',
    threshold: 10,
    severity: 'mild',
    message: 'Asymmetry observed between left and right shoulder reach.',
    coaching: 'Focus additional mobility work on the more restricted side.',
  },
];

export const singleLegBalanceRules: AssessmentRule[] = [
  {
    id: 'slb-hip-stability',
    name: 'Hip Instability',
    testType: 'single_leg_balance',
    category: 'Hip Stability',
    metricKey: 'hipStability',
    operator: '>',
    threshold: 8,
    severity: 'mild',
    message: 'Hip lateral sway observed during single-leg balance.',
    coaching: 'Single-leg Romanian deadlifts and lateral band walks can improve hip stability.',
  },
  {
    id: 'slb-hip-stability-mod',
    name: 'Significant Hip Instability',
    testType: 'single_leg_balance',
    category: 'Hip Stability',
    metricKey: 'hipStability',
    operator: '>',
    threshold: 15,
    severity: 'moderate',
    message: 'Significant hip instability during single-leg balance.',
    coaching: 'Focus on gluteus medius strengthening and proprioception exercises.',
  },
  {
    id: 'slb-pelvic-drop',
    name: 'Pelvic Drop',
    testType: 'single_leg_balance',
    category: 'Pelvic Drop',
    metricKey: 'pelvicDrop',
    operator: '>',
    threshold: 5,
    severity: 'mild',
    message: 'Pelvic drop observed on the non-stance side (Trendelenburg sign).',
    coaching: 'Hip abductor strengthening, especially side-lying leg lifts.',
  },
  {
    id: 'slb-trunk-sway',
    name: 'Trunk Sway',
    testType: 'single_leg_balance',
    category: 'Trunk Sway',
    metricKey: 'trunkSway',
    operator: '>',
    threshold: 8,
    severity: 'mild',
    message: 'Trunk sway observed during single-leg balance.',
    coaching: 'Core stability exercises like planks and Pallof presses.',
  },
];

export const forwardBendRules: AssessmentRule[] = [
  {
    id: 'fb-flexion-limited',
    name: 'Limited Spinal Flexion',
    testType: 'forward_bend',
    category: 'Spinal Flexion',
    metricKey: 'spinalFlexion',
    operator: '<',
    threshold: 60,
    severity: 'mild',
    message: 'Spinal flexion range appears limited during forward bend.',
    coaching: 'Hamstring and lower back stretches can help improve forward bend range.',
  },
  {
    id: 'fb-hip-hinge-limited',
    name: 'Limited Hip Hinge',
    testType: 'forward_bend',
    category: 'Hip Hinge',
    metricKey: 'hipHinge',
    operator: '>',
    threshold: 120,
    severity: 'mild',
    message: 'Hip hinge appears limited — bending more through the spine than hips.',
    coaching: 'Practice hip hinge patterns with a dowel or wall touch drill.',
  },
  {
    id: 'fb-symmetry',
    name: 'Forward Bend Asymmetry',
    testType: 'forward_bend',
    category: 'Symmetry',
    metricKey: 'symmetry',
    operator: '<',
    threshold: 80,
    severity: 'mild',
    message: 'Asymmetry observed during forward bend.',
    coaching: 'Unilateral hamstring and hip stretches may help balance flexibility.',
  },
];
