/**
 * Standing posture assessment rules.
 * Evidence-based thresholds for common postural deviations.
 */

import type { AssessmentRule } from '../../types';

export const standingPostureRules: AssessmentRule[] = [
  // --- Head Position ---
  {
    id: 'sp-head-mild',
    name: 'Mild Forward Head',
    testType: 'standing_posture',
    category: 'Head Position',
    metricKey: 'forwardHeadAngle',
    operator: '>',
    threshold: 8,
    severity: 'mild',
    message: 'Slight forward head posture observed.',
    coaching: 'Try gently tucking your chin and aligning your ears over your shoulders.',
  },
  {
    id: 'sp-head-moderate',
    name: 'Moderate Forward Head',
    testType: 'standing_posture',
    category: 'Head Position',
    metricKey: 'forwardHeadAngle',
    operator: '>',
    threshold: 15,
    severity: 'moderate',
    message: 'Moderate forward head posture observed.',
    coaching: 'Chin tuck exercises and upper back strengthening may help improve alignment.',
  },
  {
    id: 'sp-head-significant',
    name: 'Significant Forward Head',
    testType: 'standing_posture',
    category: 'Head Position',
    metricKey: 'forwardHeadAngle',
    operator: '>',
    threshold: 25,
    severity: 'significant',
    message: 'Significant forward head posture observed.',
    coaching: 'Consider consulting a professional. Regular chin tucks and posture awareness exercises are recommended.',
  },

  // --- Shoulder Symmetry ---
  {
    id: 'sp-shoulder-mild',
    name: 'Mild Shoulder Elevation',
    testType: 'standing_posture',
    category: 'Shoulder Symmetry',
    metricKey: 'shoulderHeightDiff',
    operator: 'outside',
    threshold: [-3, 3],
    severity: 'mild',
    message: 'Mild shoulder height asymmetry observed.',
    coaching: 'Upper trapezius stretches on the elevated side may help.',
  },
  {
    id: 'sp-shoulder-moderate',
    name: 'Moderate Shoulder Elevation',
    testType: 'standing_posture',
    category: 'Shoulder Symmetry',
    metricKey: 'shoulderHeightDiff',
    operator: 'outside',
    threshold: [-5, 5],
    severity: 'moderate',
    message: 'Moderate shoulder height difference observed.',
    coaching: 'Consider stretching the elevated side and strengthening the lower side.',
  },
  {
    id: 'sp-shoulder-rotation-mild',
    name: 'Mild Shoulder Rotation',
    testType: 'standing_posture',
    category: 'Shoulder Symmetry',
    metricKey: 'shoulderRotation',
    operator: 'outside',
    threshold: [-5, 5],
    severity: 'mild',
    message: 'Mild shoulder rotation observed. One shoulder appears more forward than the other.',
    coaching: 'Chest stretches and upper back rows can help balance shoulder position.',
  },

  // --- Pelvis ---
  {
    id: 'sp-pelvis-tilt-mild',
    name: 'Mild Pelvic Tilt',
    testType: 'standing_posture',
    category: 'Pelvis',
    metricKey: 'pelvicTilt',
    operator: 'outside',
    threshold: [-3, 3],
    severity: 'mild',
    message: 'Mild lateral pelvic tilt observed.',
    coaching: 'Hip abductor strengthening on the lower side may help level the pelvis.',
  },
  {
    id: 'sp-pelvis-tilt-moderate',
    name: 'Moderate Pelvic Tilt',
    testType: 'standing_posture',
    category: 'Pelvis',
    metricKey: 'pelvicTilt',
    operator: 'outside',
    threshold: [-5, 5],
    severity: 'moderate',
    message: 'Moderate lateral pelvic tilt observed.',
    coaching: 'Consider gluteus medius strengthening and hip flexor stretching.',
  },
  {
    id: 'sp-hip-shift-mild',
    name: 'Mild Hip Shift',
    testType: 'standing_posture',
    category: 'Pelvis',
    metricKey: 'hipShift',
    operator: '>',
    threshold: 5,
    severity: 'mild',
    message: 'Mild lateral hip shift observed.',
    coaching: 'Practice standing with weight evenly distributed on both feet.',
  },

  // --- Knees ---
  {
    id: 'sp-knee-valgus-left-mild',
    name: 'Mild Left Knee Valgus',
    testType: 'standing_posture',
    category: 'Knees',
    metricKey: 'leftKneeAngle',
    operator: '>',
    threshold: 5,
    severity: 'mild',
    message: 'Mild left knee valgus (inward collapse) observed.',
    coaching: 'Clamshell exercises and single-leg balance can help improve knee alignment.',
  },
  {
    id: 'sp-knee-valgus-right-mild',
    name: 'Mild Right Knee Valgus',
    testType: 'standing_posture',
    category: 'Knees',
    metricKey: 'rightKneeAngle',
    operator: '>',
    threshold: 5,
    severity: 'mild',
    message: 'Mild right knee valgus (inward collapse) observed.',
    coaching: 'Clamshell exercises and single-leg balance can help improve knee alignment.',
  },

  // --- Trunk ---
  {
    id: 'sp-trunk-lean-mild',
    name: 'Mild Trunk Lean',
    testType: 'standing_posture',
    category: 'Trunk',
    metricKey: 'trunkLean',
    operator: 'outside',
    threshold: [-4, 4],
    severity: 'mild',
    message: 'Mild trunk lean observed.',
    coaching: 'Core strengthening exercises can help improve trunk alignment.',
  },
  {
    id: 'sp-trunk-lean-moderate',
    name: 'Moderate Trunk Lean',
    testType: 'standing_posture',
    category: 'Trunk',
    metricKey: 'trunkLean',
    operator: 'outside',
    threshold: [-8, 8],
    severity: 'moderate',
    message: 'Moderate trunk lean observed.',
    coaching: 'Lateral core strengthening and postural awareness exercises recommended.',
  },

  // --- Weight Distribution ---
  {
    id: 'sp-weight-shift-mild',
    name: 'Mild Weight Shift',
    testType: 'standing_posture',
    category: 'Weight Distribution',
    metricKey: 'weightShift',
    operator: '>',
    threshold: 5,
    severity: 'mild',
    message: 'Weight appears shifted to one side.',
    coaching: 'Practice standing with awareness of equal weight on both feet.',
  },
];
